---
apiVersion: v1
kind: ConfigMap
metadata:
  name: litmus-portal-admin-config
  namespace: ${OKTETO_NAMESPACE}
data:
  K8s-mode: namespace
  SubscriberNamespace: ${OKTETO_NAMESPACE}
  DataBaseServer: "mongodb://mongo-service:27017"
  JWTSecret: "litmus-portal@123"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: litmusportal-frontend
  namespace: ${OKTETO_NAMESPACE}
  labels:
    component: litmusportal-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      component: litmusportal-frontend
  template:
    metadata:
      labels:
        component: litmusportal-frontend
    spec:
      containers:
        - name: litmusportal-frontend
          image: litmuschaos/litmusportal-frontend:ci
          resources:
            limits:
              cpu: 150m
              memory: 200Mi
          imagePullPolicy: Always
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: litmusportal-frontend-service
  namespace: ${OKTETO_NAMESPACE}
spec:
  type: NodePort
  ports:
    - name: http
      port: 9091
      targetPort: 80
  selector:
    component: litmusportal-frontend
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: self-deployer-namespace-account
  namespace: ${OKTETO_NAMESPACE}
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: Role
metadata:
  name: deployer-namespace
  namespace: ${OKTETO_NAMESPACE}
  labels:
    name: deployer-namespace
rules:
  - apiGroups:
      - ""
    resources:
      - serviceaccounts
      - services
      - configmaps
      - pods
    verbs:
      - "create"
      - "delete"
      - "patch"
      - "update"
  - apiGroups:
      - "rbac.authorization.k8s.io"
    resources:
      - roles
      - rolebindings
    verbs:
      - "create"
      - "delete"
      - "patch"
      - "update"
  - apiGroups:
      - "apps"
    resources:
      - deployments
    verbs:
      - "create"
      - "delete"
      - "patch"
      - "update"
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: RoleBinding
metadata:
  name: deployer-namespace-rb
  namespace: ${OKTETO_NAMESPACE}
subjects:
  - kind: ServiceAccount
    name: self-deployer-namespace-account
    namespace: ${OKTETO_NAMESPACE}
roleRef:
  kind: Role
  name: deployer-namespace
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: litmus-server-account
  namespace: ${OKTETO_NAMESPACE}
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: Role
metadata:
  name: litmus-server
  namespace: ${OKTETO_NAMESPACE}
  labels:
    name: litmus-server
rules:
  - apiGroups:
      - ""
    resources:
      - pods
      - pods/exec
    verbs:
      - create
      - patch
      - update
  - apiGroups:
      - "apps"
    resources:
      - deployments
    verbs:
      - create
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: RoleBinding
metadata:
  name: litmus-server-rb
  namespace: ${OKTETO_NAMESPACE}
subjects:
  - kind: ServiceAccount
    name: litmus-server-account
    namespace: ${OKTETO_NAMESPACE}
roleRef:
  kind: Role
  name: litmus-server
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: litmusportal-server
  namespace: ${OKTETO_NAMESPACE}
  labels:
    component: litmusportal-server
spec:
  replicas: 1
  selector:
    matchLabels:
      component: litmusportal-server
  template:
    metadata:
      labels:
        component: litmusportal-server
    spec:
      containers:
        - name: graphql-server
          image: litmuschaos/litmusportal-server:ci
          resources:
            limits:
              cpu: 200m
              memory: 400Mi
          env:
            - name: DB_SERVER
              valueFrom:
                configMapKeyRef:
                  name: litmus-portal-admin-config
                  key: DataBaseServer
            - name: JWT_SECRET
              valueFrom:
                configMapKeyRef:
                  name: litmus-portal-admin-config
                  key: JWTSecret
            - name: EXTERNAL_ADDRESS
              value: ""
            - name: SERVICE_ADDRESS
              value: "http://litmusportal-server-service:9002"
            - name: SELF_CLUSTER
              value: "true"
            - name: SUBSCRIBER_IMAGE
              value: "litmuschaos/litmusportal-subscriber:ci"
            - name: SUBSCRIBER_SCOPE
              valueFrom:
                configMapKeyRef:
                  name: litmus-portal-admin-config
                  key: K8s-mode
            - name: AGENT_SCOPE
              valueFrom:
                configMapKeyRef:
                  name: litmus-portal-admin-config
                  key: K8s-mode
            - name: SUBSCRIBER_NAMESPACE
              valueFrom:
                configMapKeyRef:
                  name: litmus-portal-admin-config
                  key: SubscriberNamespace
            - name: AGENT_NAMESPACE
              valueFrom:
                configMapKeyRef:
                  name: litmus-portal-admin-config
                  key: SubscriberNamespace
            - name: DEPLOYER_IMAGE
              value: "litmuschaos/litmusportal-self-deployer:ci"
            - name: DEPLOYER_NAMESPACE
              valueFrom:
                configMapKeyRef:
                  name: litmus-portal-admin-config
                  key: SubscriberNamespace
            - name: ARGO_SERVER_IMAGE
              value: "argoproj/argocli:v2.9.3"
            - name: ARGO_WORKFLOW_CONTROLLER_IMAGE
              value: "argoproj/workflow-controller:v2.9.3"
            - name: ARGO_WORKFLOW_EXECUTOR_IMAGE
              value: "argoproj/argoexec:v2.9.3"
            - name: LITMUS_CHAOS_OPERATOR_IMAGE
              value: "litmuschaos/chaos-operator:1.8.2"
            - name: LITMUS_CHAOS_RUNNER_IMAGE
              value: "litmuschaos/chaos-runner:1.8.2"
          ports:
            - containerPort: 8080
          imagePullPolicy: Always
        - name: auth-server
          image: litmuschaos/litmusportal-auth-server:ci
          resources:
            limits:
              cpu: 200m
              memory: 250Mi
          env:
            - name: DB_SERVER
              valueFrom:
                configMapKeyRef:
                  name: litmus-portal-admin-config
                  key: DataBaseServer
            - name: JWT_SECRET
              valueFrom:
                configMapKeyRef:
                  name: litmus-portal-admin-config
                  key: JWTSecret
            - name: ADMIN_USERNAME
              value: "admin"
            - name: ADMIN_PASSWORD
              value: "litmus"
          ports:
            - containerPort: 3000
          imagePullPolicy: Always
      serviceAccountName: litmus-server-account
---
apiVersion: v1
kind: Service
metadata:
  name: litmusportal-server-service
  namespace: ${OKTETO_NAMESPACE}
spec:
  type: ClusterIP
  ports:
    - name: graphql-server
      port: 9002
      targetPort: 8080
    - name: auth-server
      port: 9003
      targetPort: 3000
  selector:
    component: litmusportal-server
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo
  namespace: ${OKTETO_NAMESPACE}
  labels:
    app: mongo
spec:
  replicas: 1
  selector:
    matchLabels:
      component: database
  template:
    metadata:
      labels:
        component: database
    spec:
      containers:
        - name: mongo
          image: mongo:4.2.8
          resources:
            limits:
              cpu: 200m
              memory: 400Mi
          ports:
            - containerPort: 27017
          imagePullPolicy: Always
          volumeMounts:
            - name: mongo-persistent-storage
              mountPath: /data/db
      volumes:
        - name: mongo-persistent-storage
          persistentVolumeClaim:
            claimName: mongo-pv-claim
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongo-pv-claim
  namespace: ${OKTETO_NAMESPACE}
  labels:
    app: mongo
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 4Gi
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: mongo
  name: mongo-service
  namespace: ${OKTETO_NAMESPACE}
spec:
  ports:
    - port: 27017
      targetPort: 27017
  selector:
    component: database
